{{- if .Values.kibana.ingress.enabled -}}
{{- $servicePort := .Values.kibana.service.port -}}
{{- $ingressPath := .Values.kibana.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "elasticsearch-operator.fullname" . }}-kibana
  labels: {{ include "elasticsearch-operator.labels" . | indent 4 }}
{{- with .Values.kibana.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.kibana.ingress.tls }}
  tls:
  {{- range .Values.kibana.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.kibana.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath}}
            backend:
              serviceName: {{ template "elasticsearch-operator.fullname" . }}-kibana
              servicePort: {{ .Values.kibana.service.port }}}}
  {{- end }}
{{- end }}
